CREATE TABLE companies(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL
);

CREATE TABLE users(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL,
  name VARCHAR NOT NULL,

  FOREIGN KEY(company_id) REFERENCES companies(id) ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE categories(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name VARCHAR NOT NULL,
  parent_id INTEGER,

  FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE
);